from src.common import config
from typing import Union

from src.common.logger import logger
from src.infrastructure.system_utils import load_language_map

_language_cache = {}
_missing_log_cache = set()  # tránh spam log

LANGUAGE_DIR = config.language_dir


def get_text(keyword: str, lang: str = "en") -> str:
    """
    Trả về text đã dịch từ keyword sang ngôn ngữ lang.
    - Nếu lang là 'en' => trả lại keyword gốc.
    - Nếu file lang không tồn tại => log 1 lần, trả lại keyword gốc.
    - Nếu thiếu key trong lang map => log 1 lần, trả lại keyword gốc.
    """
    key = keyword.strip().lower()

    # Nếu lang là en, trả về luôn
    if lang == "en":
        return keyword

    lang_map = load_language_map(lang)
    if lang_map is None:
        return keyword

    text = lang_map.get(key)
    if text is not None:
        return text

    # Nếu thiếu key, log 1 lần để tiện bổ sung
    missing_key = f"{lang}::{key}"
    if missing_key not in _missing_log_cache:
        logger.warn(f"[WARN] Missing translation for key '{key}' in lang '{lang}'. Please add to {lang}.json.")
        _missing_log_cache.add(missing_key)

    return keyword


def translate_keywords(keywords: Union[str, list[str]], lang: str = 'en') -> Union[str, list[str]]:
    if isinstance(keywords, str):
        return get_text(keywords, lang)
    return [get_text(k, lang) for k in keywords]


def get_accept_language(country_code: str) -> str:
    country_code = country_code.upper()

    mapping = {
        "US": "en-US,en;q=0.9",
        "VN": "vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7",
        "JP": "ja-JP,ja;q=0.9,en-US;q=0.8,en;q=0.7",
        "MX": "es-MX,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "CA": "en-CA,en;q=0.9,fr-CA;q=0.8",
        "AU": "en-AU,en;q=0.9",
        "NZ": "en-NZ,en;q=0.9",
        "NL": "nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7",
        "GB": "en-GB,en;q=0.9",
        "FR": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "DE": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
        "RU": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
        "IN": "en-IN,en;q=0.9,hi;q=0.8",
        "CN": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        "TW": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        "HK": "zh-HK,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        "ID": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
        "TH": "th-TH,th;q=0.9,en-US;q=0.8,en;q=0.7",
        "ES": "es-ES,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "IT": "it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7",
        "KR": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
        "BR": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
        "PT": "pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7",
        "TR": "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7",
        "BE": "nl-BE,nl;q=0.9,fr-BE;q=0.8,en;q=0.7",
        "CH": "de-CH,de;q=0.9,fr-CH;q=0.8,it-CH;q=0.7,en-US;q=0.6",
        "PL": "pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7",
        "PH": "en-PH,en;q=0.9,tl;q=0.8",
        "MY": "ms-MY,ms;q=0.9,en-US;q=0.8,en;q=0.7",
        "SA": "ar-SA,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "EG": "ar-EG,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "IR": "fa-IR,fa;q=0.9,en-US;q=0.8,en;q=0.7",
        "NG": "en-NG,en;q=0.9",
        "ZA": "en-ZA,en;q=0.9",
        "KE": "en-KE,en;q=0.9",
        "PK": "en-PK,en;q=0.9,ur;q=0.8",
        "BD": "en-BD,en;q=0.9,bn;q=0.8",
        "AR": "es-AR,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "CL": "es-CL,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "CO": "es-CO,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "PE": "es-PE,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "VE": "es-VE,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "UA": "uk-UA,uk;q=0.9,ru;q=0.8,en-US;q=0.7",
        "SE": "sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7",
        "NO": "no-NO,no;q=0.9,en-US;q=0.8,en;q=0.7",
        "FI": "fi-FI,fi;q=0.9,en-US;q=0.8,en;q=0.7",
        "DK": "da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7",
        "GR": "el-GR,el;q=0.9,en-US;q=0.8,en;q=0.7",
        "CZ": "cs-CZ,cs;q=0.9,en-US;q=0.8,en;q=0.7",
        "RO": "ro-RO,ro;q=0.9,en-US;q=0.8,en;q=0.7",
        "HU": "hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7",
        "IL": "he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7",
        "AE": "ar-AE,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "MO": "zh-MO,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        "SK": "sk-SK,sk;q=0.9,en-US;q=0.8,en;q=0.7",
        "BN": "ms-BN,ms;q=0.9,en-US;q=0.8,en;q=0.7",
        "MN": "mn-MN,mn;q=0.9,en-US;q=0.8,en;q=0.7",
        "SG": "en-SG,en;q=0.9,zh;q=0.8,ms;q=0.7,ta;q=0.6",
        "MM": "my-MM,my;q=0.9,en-US;q=0.8,en;q=0.7",
        "BT": "dz-BT,dz;q=0.9,en-US;q=0.8,en;q=0.7",
        "MV": "dv-MV,dv;q=0.9,en-US;q=0.8,en;q=0.7",
        "NP": "ne-NP,ne;q=0.9,en-US;q=0.8,en;q=0.7",
        "LK": "si-LK,si;q=0.9,ta;q=0.8,en-US;q=0.7,en;q=0.6",
        "BH": "ar-BH,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "KW": "ar-KW,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "OM": "ar-OM,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "QA": "ar-QA,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "YE": "ar-YE,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "CY": "el-CY,el;q=0.9,tr;q=0.8,en-US;q=0.7,en;q=0.6",
        "IQ": "ar-IQ,ar;q=0.9,ku;q=0.8,en-US;q=0.7,en;q=0.6",
        "JO": "ar-JO,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "LB": "ar-LB,ar;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6",
        "PS": "ar-PS,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "SY": "ar-SY,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "AF": "fa-AF,fa;q=0.9,ps;q=0.8,en-US;q=0.7,en;q=0.6",
        "AM": "hy-AM,hy;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "AZ": "az-Latn-AZ,az;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "KZ": "kk-KZ,kk;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "KG": "ky-KG,ky;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "TJ": "tg-TJ,tg;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "TM": "tk-TM,tk;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "UZ": "uz-Latn-UZ,uz;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "GE": "ka-GE,ka;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "TL": "pt-TL,pt;q=0.9,tet;q=0.8,en-US;q=0.7,en;q=0.6",
        "KH": "km-KH,km;q=0.9,en-US;q=0.8,en;q=0.7",
        "RS": "sr-RS,sr;q=0.9,en-US;q=0.8,en;q=0.7",
        "AL": "sq-AL,sq;q=0.9,en-US;q=0.8,en;q=0.7",
        "BA": "bs-BA,bs;q=0.9,hr;q=0.8,sr;q=0.7,en-US;q=0.6",
        "LU": "fr-LU,fr;q=0.9,de-LU;q=0.8,lb;q=0.7,en-US;q=0.6",
        "BY": "be-BY,be;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
        "AT": "de-AT,de;q=0.9,en-US;q=0.8,en;q=0.7",
        "IE": "en-IE,en;q=0.9",
        "VA": "it-VA,it;q=0.9,la;q=0.8,en-US;q=0.7,en;q=0.6",
        "LV": "lv-LV,lv;q=0.9,en-US;q=0.8,en;q=0.7",
        "LT": "lt-LT,lt;q=0.9,en-US;q=0.8,en;q=0.7",
        "MD": "ro-MD,ro;q=0.9,ru;q=0.8,en-US;q=0.7",
        "MC": "fr-MC,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "IS": "is-IS,is;q=0.9,en-US;q=0.8,en;q=0.7",
        "MT": "mt-MT,mt;q=0.9,en-US;q=0.8,en;q=0.7",
        "EE": "et-EE,et;q=0.9,en-US;q=0.8,en;q=0.7",
        "HR": "hr-HR,hr;q=0.9,en-US;q=0.8,en;q=0.7",
        "MK": "mk-MK,mk;q=0.9,en-US;q=0.8,en;q=0.7",
        "BG": "bg-BG,bg;q=0.9,en-US;q=0.8,en;q=0.7",
        "NA": "en-US,en;q=0.9",
        "GT": "es-GT,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "CU": "es-CU,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "JM": "en-JM,en;q=0.9",
        "LC": "en-LC,en;q=0.9",
        "PA": "es-PA,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "HN": "es-HN,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "TT": "en-TT,en;q=0.9",
        "EC": "es-EC,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "DO": "es-DO,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "SV": "es-SV,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "PR": "es-PR,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "CR": "es-CR,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "NI": "es-NI,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "UY": "es-UY,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "BO": "es-BO,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "PY": "es-PY,es;q=0.9,en-US;q=0.8,en;q=0.7",
        "FJ": "en-FJ,en;q=0.9",
        "PW": "en-PW,en;q=0.9",
        "MA": "ar-MA,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "TN": "ar-TN,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "CI": "fr-CI,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "LY": "ar-LY,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "BF": "fr-BF,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "CG": "fr-CG,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "MG": "fr-MG,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "MZ": "pt-MZ,pt;q=0.9,en-US;q=0.8,en;q=0.7",
        "ET": "am-ET,am;q=0.9,en-US;q=0.8,en;q=0.7",
        "GH": "en-GH,en;q=0.9",
        "DZ": "ar-DZ,ar;q=0.9,en-US;q=0.8,en;q=0.7",
        "ML": "fr-ML,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "SN": "fr-SN,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "AO": "pt-AO,pt;q=0.9,en-US;q=0.8,en;q=0.7",
        "GA": "ka-GE,ka;q=0.9,ru;q=0.8,en;q=0.7"
    }

    return mapping.get(country_code, "en-US,en;q=0.9")


def get_locale_from_country_code(country_code: str) -> str:
    country_code = country_code.upper() if country_code else ""

    mapping = {
        "US": "en_US",
        "VN": "vi_VN",
        "JP": "ja_JP",
        "MX": "es_MX",
        "CA": "en_CA",
        "AU": "en_AU",
        "NZ": "en_NZ",
        "NL": "nl_NL",
        "GB": "en_GB",
        "FR": "fr_FR",
        "DE": "de_DE",
        "RU": "ru_RU",
        "IN": "en_IN",
        "CN": "zh_CN",
        "TW": "zh_TW",
        "HK": "zh_HK",
        "ID": "id_ID",
        "TH": "th_TH",
        "ES": "es_ES",
        "IT": "it_IT",
        "KR": "ko_KR",
        "BR": "pt_BR",
        "PT": "pt_PT",
        "TR": "tr_TR",
        "BE": "nl_BE",
        "CH": "de_CH",
        "PL": "pl_PL",
        "PH": "en_PH",
        "MY": "ms_MY",
        "SA": "ar_SA",
        "EG": "ar_EG",
        "IR": "fa_IR",
        "NG": "en_NG",
        "ZA": "en_ZA",
        "KE": "en_KE",
        "PK": "en_PK",
        "BD": "en_BD",
        "AR": "es_AR",
        "CL": "es_CL",
        "CO": "es_CO",
        "PE": "es_PE",
        "VE": "es_VE",
        "UA": "uk_UA",
        "SE": "sv_SE",
        "NO": "no_NO",
        "FI": "fi_FI",
        "DK": "da_DK",
        "GR": "el_GR",
        "CZ": "cs_CZ",
        "RO": "ro_RO",
        "HU": "hu_HU",
        "IL": "he_IL",
        "AE": "ar_AE",
        "MO": "zh_MO",
        "SK": "sk_SK",
        "BN": "ms_BN",
        "MN": "mn_MN",
        "SG": "en_SG",
        "MM": "my_MM",
        "BT": "dz_BT",
        "MV": "dv_MV",
        "NP": "ne_NP",
        "LK": "si_LK",
        "BH": "ar_BH",
        "KW": "ar_KW",
        "OM": "ar_OM",
        "QA": "ar_QA",
        "YE": "ar_YE",
        "CY": "el_CY",
        "IQ": "ar_IQ",
        "JO": "ar_JO",
        "LB": "ar_LB",
        "PS": "ar_PS",
        "SY": "ar_SY",
        "AF": "fa_AF",
        "AM": "hy_AM",
        "AZ": "az_Latn_AZ",
        "KZ": "kk_KZ",
        "KG": "ky_KG",
        "TJ": "tg_TJ",
        "TM": "tk_TM",
        "UZ": "uz_Latn_UZ",
        "GE": "ka_GE",
        "TL": "pt_TL",
        "KH": "km_KH",
        "RS": "sr_RS",
        "AL": "sq_AL",
        "BA": "bs_BA",
        "LU": "fr_LU",
        "BY": "be_BY",
        "AT": "de_AT",
        "IE": "en_IE",
        "VA": "it_VA",
        "LV": "lv_LV",
        "LT": "lt_LT",
        "MD": "ro_MD",
        "MC": "fr_MC",
        "IS": "is_IS",
        "MT": "mt_MT",
        "EE": "et_EE",
        "HR": "hr_HR",
        "MK": "mk_MK",
        "BG": "bg_BG",
        "NA": "en_NA",
        "GT": "es_GT",
        "CU": "es_CU",
        "JM": "en_JM",
        "LC": "en_LC",
        "PA": "es_PA",
        "HN": "es_HN",
        "TT": "en_TT",
        "EC": "es_EC",
        "DO": "es_DO",
        "SV": "es_SV",
        "PR": "es_PR",
        "CR": "es_CR",
        "NI": "es_NI",
        "UY": "es_UY",
        "BO": "es_BO",
        "PY": "es_PY",
        "FJ": "en_FJ",
        "PW": "en_PW",
        "MA": "ar_MA",
        "TN": "ar_TN",
        "CI": "fr_CI",
        "LY": "ar_LY",
        "BF": "fr_BF",
        "CG": "fr_CG",
        "MG": "mg_MG",
        "MZ": "pt_MZ",
        "ET": "am_ET",
        "GH": "en_GH",
        "DZ": "ar_DZ",
        "ML": "fr_ML",
        "SN": "fr_SN",
        "AO": "pt_AO",
        "GA": "fr_GA",
    }

    return mapping.get(country_code, "en_US")
