# Form implementation generated from reading ui file 'device_management.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MetaAcctXpert(object):
    def setupUi(self, MetaAcctXpert):
        MetaAcctXpert.setObjectName("MetaAcctXpert")
        MetaAcctXpert.resize(1720, 800)
        MetaAcctXpert.setMinimumSize(QtCore.QSize(1240, 800))
        MetaAcctXpert.setStyleSheet("font-size: 14px;\n"
"background-color: rgb(237, 237, 237);")
        self.centralwidget = QtWidgets.QWidget(parent=MetaAcctXpert)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.siderbar = QtWidgets.QFrame(parent=self.centralwidget)
        self.siderbar.setMinimumSize(QtCore.QSize(200, 0))
        self.siderbar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.siderbar.setStyleSheet("QFrame {\n"
"    background-color: #00AEEF;  /* màu xanh sidebar */\n"
"    border: 0;\n"
"}\n"
"")
        self.siderbar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.siderbar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.siderbar.setObjectName("siderbar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.siderbar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_sidebar_header = QtWidgets.QFrame(parent=self.siderbar)
        self.frame_sidebar_header.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_sidebar_header.setStyleSheet("border: 0;")
        self.frame_sidebar_header.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDialableCharactersOnly)
        self.frame_sidebar_header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_sidebar_header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_sidebar_header.setObjectName("frame_sidebar_header")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_sidebar_header)
        self.verticalLayout.setContentsMargins(12, 12, 12, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(parent=self.frame_sidebar_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 150))
        self.logo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/images/statics/facebook-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.frame_version_container = QtWidgets.QFrame(parent=self.frame_sidebar_header)
        self.frame_version_container.setStyleSheet("border: 0;")
        self.frame_version_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_version_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_version_container.setObjectName("frame_version_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_version_container)
        self.horizontalLayout_6.setContentsMargins(0, 12, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_version = QtWidgets.QFrame(parent=self.frame_version_container)
        self.frame_version.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_version.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_version.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_version.setStyleSheet("border: 0;")
        self.frame_version.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_version.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_version.setObjectName("frame_version")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_version)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_version = QtWidgets.QLabel(parent=self.frame_version)
        self.label_version.setStyleSheet("color: #fff;\n"
"font-weight: bold;\n"
"font-size: 14px;")
        self.label_version.setObjectName("label_version")
        self.horizontalLayout.addWidget(self.label_version)
        self.version = QtWidgets.QLabel(parent=self.frame_version)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.version.setFont(font)
        self.version.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.version.setObjectName("version")
        self.horizontalLayout.addWidget(self.version)
        self.horizontalLayout_6.addWidget(self.frame_version)
        self.verticalLayout.addWidget(self.frame_version_container)
        self.verticalLayout_3.addWidget(self.frame_sidebar_header)
        self.frame_button = QtWidgets.QFrame(parent=self.siderbar)
        self.frame_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_button.setAutoFillBackground(False)
        self.frame_button.setStyleSheet("QToolButton {\n"
"    background-color: #00AEEF;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border: none;                /* bỏ viền */\n"
"    text-align: left;            /* chữ căn trái */\n"
"    padding: 20px 12px;           /* khoảng cách trong nút */\n"
"    font-weight: bold;\n"
"    border-radius: 0px;          /* vuông góc */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #0095D9;   /* xanh hover */\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"    background-color: #007ACC;   /* xanh đậm khi active */\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 0;\n"
"}")
        self.frame_button.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_button.setObjectName("frame_button")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_button)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButton_facebook = QtWidgets.QToolButton(parent=self.frame_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_facebook.sizePolicy().hasHeightForWidth())
        self.toolButton_facebook.setSizePolicy(sizePolicy)
        self.toolButton_facebook.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_facebook.setStyleSheet("QToolButton {\n"
"    padding-left: 20px;\n"
"    border: 0;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/statics/facebook.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_facebook.setIcon(icon)
        self.toolButton_facebook.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_facebook.setCheckable(True)
        self.toolButton_facebook.setChecked(True)
        self.toolButton_facebook.setAutoExclusive(True)
        self.toolButton_facebook.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_facebook.setObjectName("toolButton_facebook")
        self.verticalLayout_2.addWidget(self.toolButton_facebook)
        self.toolButton_settings = QtWidgets.QToolButton(parent=self.frame_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_settings.sizePolicy().hasHeightForWidth())
        self.toolButton_settings.setSizePolicy(sizePolicy)
        self.toolButton_settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_settings.setStyleSheet("QToolButton {\n"
"    padding-left: 20px;\n"
"    border: 0;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/statics/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_settings.setIcon(icon1)
        self.toolButton_settings.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_settings.setCheckable(True)
        self.toolButton_settings.setChecked(False)
        self.toolButton_settings.setAutoExclusive(True)
        self.toolButton_settings.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_settings.setObjectName("toolButton_settings")
        self.verticalLayout_2.addWidget(self.toolButton_settings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_button)
        self.horizontalLayout_5.addWidget(self.siderbar)
        self.frame_main_content = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_main_content.setStyleSheet("QFrame {\n"
"    border: 0;\n"
"}")
        self.frame_main_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main_content.setObjectName("frame_main_content")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_main_content)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_main_content)
        self.stackedWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_faceook_creator_management = QtWidgets.QWidget()
        self.page_faceook_creator_management.setStyleSheet("QFrame {\n"
"    border: 0;\n"
"}")
        self.page_faceook_creator_management.setObjectName("page_faceook_creator_management")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_faceook_creator_management)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_right_header_facebook_creator = QtWidgets.QFrame(parent=self.page_faceook_creator_management)
        self.frame_right_header_facebook_creator.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_right_header_facebook_creator.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_right_header_facebook_creator.setStyleSheet("border: 0;\n"
"background-color: rgb(12, 103, 152);")
        self.frame_right_header_facebook_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right_header_facebook_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right_header_facebook_creator.setObjectName("frame_right_header_facebook_creator")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_right_header_facebook_creator)
        self.horizontalLayout_7.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.device_frame_label_fb_creator = QtWidgets.QFrame(parent=self.frame_right_header_facebook_creator)
        self.device_frame_label_fb_creator.setStyleSheet("border: 0;")
        self.device_frame_label_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.device_frame_label_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.device_frame_label_fb_creator.setObjectName("device_frame_label_fb_creator")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.device_frame_label_fb_creator)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.fb_creator_icon = QtWidgets.QLabel(parent=self.device_frame_label_fb_creator)
        self.fb_creator_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.fb_creator_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_creator_icon.setStyleSheet("")
        self.fb_creator_icon.setText("")
        self.fb_creator_icon.setPixmap(QtGui.QPixmap(":/images/statics/facebook.png"))
        self.fb_creator_icon.setScaledContents(True)
        self.fb_creator_icon.setObjectName("fb_creator_icon")
        self.horizontalLayout_12.addWidget(self.fb_creator_icon)
        self.fb_creator_label = QtWidgets.QLabel(parent=self.device_frame_label_fb_creator)
        self.fb_creator_label.setStyleSheet("color: #fff;\n"
"font-weight: bold;")
        self.fb_creator_label.setObjectName("fb_creator_label")
        self.horizontalLayout_12.addWidget(self.fb_creator_label)
        self.horizontalLayout_7.addWidget(self.device_frame_label_fb_creator)
        spacerItem1 = QtWidgets.QSpacerItem(817, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.cpu_ram_label_fb_creator = QtWidgets.QLabel(parent=self.frame_right_header_facebook_creator)
        self.cpu_ram_label_fb_creator.setStyleSheet("background: transparent;\n"
"color: #fff;\n"
"font-weight: bold;")
        self.cpu_ram_label_fb_creator.setObjectName("cpu_ram_label_fb_creator")
        self.horizontalLayout_7.addWidget(self.cpu_ram_label_fb_creator)
        self.verticalLayout_13.addWidget(self.frame_right_header_facebook_creator)
        self.frame_facebook_creator_management = QtWidgets.QFrame(parent=self.page_faceook_creator_management)
        self.frame_facebook_creator_management.setStyleSheet("")
        self.frame_facebook_creator_management.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_facebook_creator_management.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_facebook_creator_management.setObjectName("frame_facebook_creator_management")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_facebook_creator_management)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_facebook_creator_table_view = QtWidgets.QFrame(parent=self.frame_facebook_creator_management)
        self.frame_facebook_creator_table_view.setStyleSheet("QFrame {\n"
"    background-color: rgb(237, 237, 237);\n"
"    border: 1px solid rgb(26, 26, 26);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_facebook_creator_table_view.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_facebook_creator_table_view.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_facebook_creator_table_view.setObjectName("frame_facebook_creator_table_view")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_facebook_creator_table_view)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.facebook_creator_table_view = QtWidgets.QTableView(parent=self.frame_facebook_creator_table_view)
        self.facebook_creator_table_view.setMinimumSize(QtCore.QSize(0, 25))
        self.facebook_creator_table_view.setStyleSheet("QTableView {\n"
"    background-color: #fff;\n"
"    gridline-color: #dcdcdc;\n"
"    font: 14px Arial, sans-serif;\n"
"    color: #000;\n"
"    border: 0;\n"
"    selection-background-color: rgba(62, 64, 255, 128);\n"
"    selection-color: #000;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(233, 233, 233);\n"
"    color: #000;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #dcdcdc;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #357ABD;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: rgb(178, 178, 178);\n"
"    width: 5px;\n"
"    margin: 20px 0 20px 0;\n"
"    border: 1px solid #dcdcdc;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: green;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(253, 96, 8);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: rgb(178, 178, 178);\n"
"    height: 5px;\n"
"    margin: 0 20px 0 20px;\n"
"    border: 1px solid #dcdcdc;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: green;\n"
"    min-width: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(253, 96, 8);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 0px;\n"
"}")
        self.facebook_creator_table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.facebook_creator_table_view.setProperty("showDropIndicator", False)
        self.facebook_creator_table_view.setDragDropOverwriteMode(False)
        self.facebook_creator_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.facebook_creator_table_view.setSortingEnabled(True)
        self.facebook_creator_table_view.setWordWrap(False)
        self.facebook_creator_table_view.setObjectName("facebook_creator_table_view")
        self.facebook_creator_table_view.horizontalHeader().setCascadingSectionResizes(True)
        self.facebook_creator_table_view.horizontalHeader().setDefaultSectionSize(150)
        self.facebook_creator_table_view.horizontalHeader().setMinimumSectionSize(19)
        self.facebook_creator_table_view.verticalHeader().setMinimumSectionSize(21)
        self.verticalLayout_9.addWidget(self.facebook_creator_table_view)
        self.horizontalLayout_3.addWidget(self.frame_facebook_creator_table_view)
        self.verticalLayout_13.addWidget(self.frame_facebook_creator_management)
        self.frame_right_bottom_fb_creator = QtWidgets.QFrame(parent=self.page_faceook_creator_management)
        self.frame_right_bottom_fb_creator.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_right_bottom_fb_creator.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_right_bottom_fb_creator.setStyleSheet("border: 0;\n"
"background-color: rgb(12, 103, 152);")
        self.frame_right_bottom_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right_bottom_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right_bottom_fb_creator.setObjectName("frame_right_bottom_fb_creator")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_right_bottom_fb_creator)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_all_fb_creator = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_all_fb_creator.setStyleSheet("border: 0;")
        self.frame_all_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_all_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_all_fb_creator.setObjectName("frame_all_fb_creator")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.frame_all_fb_creator)
        self.horizontalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_all_fb_creator = QtWidgets.QLabel(parent=self.frame_all_fb_creator)
        self.label_all_fb_creator.setStyleSheet("color: #fff;\n"
"font-weight: bold;")
        self.label_all_fb_creator.setObjectName("label_all_fb_creator")
        self.horizontalLayout_57.addWidget(self.label_all_fb_creator)
        self.label_count_all_fb_creator = QtWidgets.QLabel(parent=self.frame_all_fb_creator)
        self.label_count_all_fb_creator.setStyleSheet("color: #fff;")
        self.label_count_all_fb_creator.setObjectName("label_count_all_fb_creator")
        self.horizontalLayout_57.addWidget(self.label_count_all_fb_creator)
        self.horizontalLayout_16.addWidget(self.frame_all_fb_creator)
        self.frame_selected_fb_creator = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_selected_fb_creator.setStyleSheet("border: 0;")
        self.frame_selected_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_selected_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_selected_fb_creator.setObjectName("frame_selected_fb_creator")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout(self.frame_selected_fb_creator)
        self.horizontalLayout_58.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_selected_fb_creator = QtWidgets.QLabel(parent=self.frame_selected_fb_creator)
        self.label_selected_fb_creator.setStyleSheet("color: rgb(254, 180, 162);\n"
"font-weight: bold;")
        self.label_selected_fb_creator.setObjectName("label_selected_fb_creator")
        self.horizontalLayout_58.addWidget(self.label_selected_fb_creator)
        self.label_count_selected_fb_creator = QtWidgets.QLabel(parent=self.frame_selected_fb_creator)
        self.label_count_selected_fb_creator.setStyleSheet("color: rgb(254, 180, 162);")
        self.label_count_selected_fb_creator.setObjectName("label_count_selected_fb_creator")
        self.horizontalLayout_58.addWidget(self.label_count_selected_fb_creator)
        self.horizontalLayout_16.addWidget(self.frame_selected_fb_creator)
        self.frame_live_fb_creator = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_live_fb_creator.setStyleSheet("border: 0;")
        self.frame_live_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_live_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_live_fb_creator.setObjectName("frame_live_fb_creator")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.frame_live_fb_creator)
        self.horizontalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_live_fb_creator = QtWidgets.QLabel(parent=self.frame_live_fb_creator)
        self.label_live_fb_creator.setStyleSheet("color: rgb(118, 219, 94);\n"
"font-weight: bold;")
        self.label_live_fb_creator.setObjectName("label_live_fb_creator")
        self.horizontalLayout_59.addWidget(self.label_live_fb_creator)
        self.label_live_count_fb_creator = QtWidgets.QLabel(parent=self.frame_live_fb_creator)
        self.label_live_count_fb_creator.setStyleSheet("color: rgb(118, 219, 94);")
        self.label_live_count_fb_creator.setObjectName("label_live_count_fb_creator")
        self.horizontalLayout_59.addWidget(self.label_live_count_fb_creator)
        self.horizontalLayout_16.addWidget(self.frame_live_fb_creator)
        self.frame_die_fb_creator = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_die_fb_creator.setStyleSheet("border: 0;")
        self.frame_die_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_die_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_die_fb_creator.setObjectName("frame_die_fb_creator")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.frame_die_fb_creator)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_die_fb_creator = QtWidgets.QLabel(parent=self.frame_die_fb_creator)
        self.label_die_fb_creator.setStyleSheet("color: rgb(253, 143, 116);\n"
"font-weight: bold;")
        self.label_die_fb_creator.setObjectName("label_die_fb_creator")
        self.horizontalLayout_60.addWidget(self.label_die_fb_creator)
        self.label_die_count_fb_creator = QtWidgets.QLabel(parent=self.frame_die_fb_creator)
        self.label_die_count_fb_creator.setStyleSheet("color: rgb(253, 143, 116);")
        self.label_die_count_fb_creator.setObjectName("label_die_count_fb_creator")
        self.horizontalLayout_60.addWidget(self.label_die_count_fb_creator)
        self.horizontalLayout_16.addWidget(self.frame_die_fb_creator)
        self.frame_error_fb_creator = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_error_fb_creator.setStyleSheet("border: 0;")
        self.frame_error_fb_creator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_error_fb_creator.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_error_fb_creator.setObjectName("frame_error_fb_creator")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.frame_error_fb_creator)
        self.horizontalLayout_61.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_error_fb_creator = QtWidgets.QLabel(parent=self.frame_error_fb_creator)
        self.label_error_fb_creator.setStyleSheet("color: #000;\n"
"font-weight: bold;")
        self.label_error_fb_creator.setObjectName("label_error_fb_creator")
        self.horizontalLayout_61.addWidget(self.label_error_fb_creator)
        self.label_error_count_fb_creator = QtWidgets.QLabel(parent=self.frame_error_fb_creator)
        self.label_error_count_fb_creator.setStyleSheet("color: #000;")
        self.label_error_count_fb_creator.setObjectName("label_error_count_fb_creator")
        self.horizontalLayout_61.addWidget(self.label_error_count_fb_creator)
        self.horizontalLayout_16.addWidget(self.frame_error_fb_creator)
        self.frame_fb_verified_count = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_fb_verified_count.setStyleSheet("border: 0;")
        self.frame_fb_verified_count.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fb_verified_count.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fb_verified_count.setObjectName("frame_fb_verified_count")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.frame_fb_verified_count)
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_fb_verified = QtWidgets.QLabel(parent=self.frame_fb_verified_count)
        self.label_fb_verified.setStyleSheet("color: rgb(255, 255, 95);\n"
"font-weight: bold;")
        self.label_fb_verified.setObjectName("label_fb_verified")
        self.horizontalLayout_62.addWidget(self.label_fb_verified)
        self.label_fb_verified_count = QtWidgets.QLabel(parent=self.frame_fb_verified_count)
        self.label_fb_verified_count.setStyleSheet("color: rgb(255, 255, 95);")
        self.label_fb_verified_count.setObjectName("label_fb_verified_count")
        self.horizontalLayout_62.addWidget(self.label_fb_verified_count)
        self.horizontalLayout_16.addWidget(self.frame_fb_verified_count)
        self.frame_fb_unverified_count = QtWidgets.QFrame(parent=self.frame_right_bottom_fb_creator)
        self.frame_fb_unverified_count.setStyleSheet("border: 0;")
        self.frame_fb_unverified_count.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fb_unverified_count.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fb_unverified_count.setObjectName("frame_fb_unverified_count")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.frame_fb_unverified_count)
        self.horizontalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_fb_unverified = QtWidgets.QLabel(parent=self.frame_fb_unverified_count)
        self.label_fb_unverified.setStyleSheet("color: rgb(255, 61, 247);\n"
"font-weight: bold;")
        self.label_fb_unverified.setObjectName("label_fb_unverified")
        self.horizontalLayout_63.addWidget(self.label_fb_unverified)
        self.label_fb_unverified_count = QtWidgets.QLabel(parent=self.frame_fb_unverified_count)
        self.label_fb_unverified_count.setStyleSheet("color: rgb(255, 61, 247);")
        self.label_fb_unverified_count.setObjectName("label_fb_unverified_count")
        self.horizontalLayout_63.addWidget(self.label_fb_unverified_count)
        self.horizontalLayout_16.addWidget(self.frame_fb_unverified_count)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.verticalLayout_13.addWidget(self.frame_right_bottom_fb_creator)
        self.stackedWidget.addWidget(self.page_faceook_creator_management)
        self.page_setting_management = QtWidgets.QWidget()
        self.page_setting_management.setStyleSheet("QFrame {\n"
"    border: 0;\n"
"}")
        self.page_setting_management.setObjectName("page_setting_management")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_setting_management)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_right_header_setting = QtWidgets.QFrame(parent=self.page_setting_management)
        self.frame_right_header_setting.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_right_header_setting.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_right_header_setting.setStyleSheet("border: 0;\n"
"background-color: rgb(12, 103, 152);")
        self.frame_right_header_setting.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right_header_setting.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right_header_setting.setObjectName("frame_right_header_setting")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_right_header_setting)
        self.horizontalLayout_8.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.setting_frame_label = QtWidgets.QFrame(parent=self.frame_right_header_setting)
        self.setting_frame_label.setStyleSheet("border: 0;")
        self.setting_frame_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.setting_frame_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.setting_frame_label.setObjectName("setting_frame_label")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.setting_frame_label)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.setting_icon = QtWidgets.QLabel(parent=self.setting_frame_label)
        self.setting_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.setting_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.setting_icon.setStyleSheet("")
        self.setting_icon.setText("")
        self.setting_icon.setPixmap(QtGui.QPixmap(":/images/statics/settings.png"))
        self.setting_icon.setScaledContents(True)
        self.setting_icon.setObjectName("setting_icon")
        self.horizontalLayout_15.addWidget(self.setting_icon)
        self.setting_label = QtWidgets.QLabel(parent=self.setting_frame_label)
        self.setting_label.setStyleSheet("color: #fff;\n"
"font-weight: bold;")
        self.setting_label.setObjectName("setting_label")
        self.horizontalLayout_15.addWidget(self.setting_label)
        self.horizontalLayout_8.addWidget(self.setting_frame_label)
        spacerItem3 = QtWidgets.QSpacerItem(817, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.cpu_ram_label_setting = QtWidgets.QLabel(parent=self.frame_right_header_setting)
        self.cpu_ram_label_setting.setStyleSheet("background: transparent;\n"
"color: #fff;\n"
"font-weight: bold;")
        self.cpu_ram_label_setting.setObjectName("cpu_ram_label_setting")
        self.horizontalLayout_8.addWidget(self.cpu_ram_label_setting)
        self.verticalLayout_15.addWidget(self.frame_right_header_setting)
        self.page_settings_frame = QtWidgets.QFrame(parent=self.page_setting_management)
        self.page_settings_frame.setStyleSheet("QFrame {\n"
"    border: 0;\n"
"}")
        self.page_settings_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page_settings_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page_settings_frame.setObjectName("page_settings_frame")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.page_settings_frame)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.setting_frame_1 = QtWidgets.QFrame(parent=self.page_settings_frame)
        self.setting_frame_1.setStyleSheet("#setting_fram_2 {border: 0;}")
        self.setting_frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.setting_frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.setting_frame_1.setObjectName("setting_frame_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.setting_frame_1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.basic_configuration = QtWidgets.QGroupBox(parent=self.setting_frame_1)
        self.basic_configuration.setMaximumSize(QtCore.QSize(16777215, 300))
        self.basic_configuration.setStyleSheet("color: #000;")
        self.basic_configuration.setObjectName("basic_configuration")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.basic_configuration)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_facebook_limit_threads = QtWidgets.QFrame(parent=self.basic_configuration)
        self.frame_facebook_limit_threads.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_facebook_limit_threads.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_facebook_limit_threads.setStyleSheet("border: 0;")
        self.frame_facebook_limit_threads.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_facebook_limit_threads.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_facebook_limit_threads.setObjectName("frame_facebook_limit_threads")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.frame_facebook_limit_threads)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.facebook_max_threads_label = QtWidgets.QLabel(parent=self.frame_facebook_limit_threads)
        self.facebook_max_threads_label.setMinimumSize(QtCore.QSize(100, 0))
        self.facebook_max_threads_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.facebook_max_threads_label.setStyleSheet("color: #000;")
        self.facebook_max_threads_label.setObjectName("facebook_max_threads_label")
        self.horizontalLayout_49.addWidget(self.facebook_max_threads_label)
        self.qspin_max_thread = QtWidgets.QSpinBox(parent=self.frame_facebook_limit_threads)
        self.qspin_max_thread.setMinimumSize(QtCore.QSize(50, 0))
        self.qspin_max_thread.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qspin_max_thread.setStyleSheet("QSpinBox {\n"
"    border: 1px solid #d1d1d1;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    background-color: #f9f9f9;\n"
"    color: #333;\n"
"    font: 12px \"Arial\";\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: #dcdcdc;\n"
"}\n"
"")
        self.qspin_max_thread.setMaximum(9999)
        self.qspin_max_thread.setProperty("value", 10)
        self.qspin_max_thread.setObjectName("qspin_max_thread")
        self.horizontalLayout_49.addWidget(self.qspin_max_thread)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.frame_facebook_limit_threads)
        self.frame_enable_proxy = QtWidgets.QFrame(parent=self.basic_configuration)
        self.frame_enable_proxy.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_enable_proxy.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_enable_proxy.setStyleSheet("border: 0;")
        self.frame_enable_proxy.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_enable_proxy.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_enable_proxy.setObjectName("frame_enable_proxy")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_enable_proxy)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_enable_proxy = QtWidgets.QLabel(parent=self.frame_enable_proxy)
        self.label_enable_proxy.setStyleSheet("color: #000;")
        self.label_enable_proxy.setObjectName("label_enable_proxy")
        self.horizontalLayout_22.addWidget(self.label_enable_proxy)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.radio_button_enable_proxy = QtWidgets.QRadioButton(parent=self.frame_enable_proxy)
        self.radio_button_enable_proxy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_enable_proxy.setStyleSheet("color: #000;")
        self.radio_button_enable_proxy.setChecked(True)
        self.radio_button_enable_proxy.setObjectName("radio_button_enable_proxy")
        self.horizontalLayout_22.addWidget(self.radio_button_enable_proxy)
        self.radio_button_disable_proxy = QtWidgets.QRadioButton(parent=self.frame_enable_proxy)
        self.radio_button_disable_proxy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_disable_proxy.setStyleSheet("color: #000;")
        self.radio_button_disable_proxy.setChecked(False)
        self.radio_button_disable_proxy.setObjectName("radio_button_disable_proxy")
        self.horizontalLayout_22.addWidget(self.radio_button_disable_proxy)
        self.verticalLayout_5.addWidget(self.frame_enable_proxy)
        self.frame_poxy_type = QtWidgets.QFrame(parent=self.basic_configuration)
        self.frame_poxy_type.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_poxy_type.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_poxy_type.setStyleSheet("border: 0;")
        self.frame_poxy_type.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_poxy_type.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_poxy_type.setObjectName("frame_poxy_type")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_poxy_type)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_proxy_type = QtWidgets.QLabel(parent=self.frame_poxy_type)
        self.label_proxy_type.setStyleSheet("color: #000;")
        self.label_proxy_type.setObjectName("label_proxy_type")
        self.horizontalLayout_21.addWidget(self.label_proxy_type)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.radio_button_http = QtWidgets.QRadioButton(parent=self.frame_poxy_type)
        self.radio_button_http.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_http.setStyleSheet("color: #000;")
        self.radio_button_http.setChecked(True)
        self.radio_button_http.setObjectName("radio_button_http")
        self.horizontalLayout_21.addWidget(self.radio_button_http)
        self.radio_button_https = QtWidgets.QRadioButton(parent=self.frame_poxy_type)
        self.radio_button_https.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_https.setStyleSheet("color: #000;")
        self.radio_button_https.setChecked(False)
        self.radio_button_https.setObjectName("radio_button_https")
        self.horizontalLayout_21.addWidget(self.radio_button_https)
        self.radio_button_socks5 = QtWidgets.QRadioButton(parent=self.frame_poxy_type)
        self.radio_button_socks5.setEnabled(True)
        self.radio_button_socks5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_socks5.setStyleSheet("color: #000;")
        self.radio_button_socks5.setChecked(False)
        self.radio_button_socks5.setObjectName("radio_button_socks5")
        self.horizontalLayout_21.addWidget(self.radio_button_socks5)
        self.verticalLayout_5.addWidget(self.frame_poxy_type)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_2.addWidget(self.basic_configuration)
        self.setting_otp_service_group = QtWidgets.QGroupBox(parent=self.setting_frame_1)
        self.setting_otp_service_group.setMaximumSize(QtCore.QSize(16777215, 300))
        self.setting_otp_service_group.setStyleSheet("color: #000;")
        self.setting_otp_service_group.setObjectName("setting_otp_service_group")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.setting_otp_service_group)
        self.verticalLayout_23.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_wait_code_timeout = QtWidgets.QFrame(parent=self.setting_otp_service_group)
        self.frame_wait_code_timeout.setStyleSheet("border: 0;")
        self.frame_wait_code_timeout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_wait_code_timeout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_wait_code_timeout.setObjectName("frame_wait_code_timeout")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.frame_wait_code_timeout)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_wait_code_timeout = QtWidgets.QLabel(parent=self.frame_wait_code_timeout)
        self.label_wait_code_timeout.setStyleSheet("color: #000;")
        self.label_wait_code_timeout.setObjectName("label_wait_code_timeout")
        self.horizontalLayout_40.addWidget(self.label_wait_code_timeout)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem8)
        self.qspin_wait_code_timeout = QtWidgets.QSpinBox(parent=self.frame_wait_code_timeout)
        self.qspin_wait_code_timeout.setMinimumSize(QtCore.QSize(150, 35))
        self.qspin_wait_code_timeout.setMaximumSize(QtCore.QSize(150, 35))
        self.qspin_wait_code_timeout.setStyleSheet("QSpinBox {\n"
"    border: 1px solid #d1d1d1;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    background-color: #f9f9f9;\n"
"    color: #333;\n"
"    font: 12px \"Arial\";\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: #dcdcdc;\n"
"}\n"
"")
        self.qspin_wait_code_timeout.setMaximum(9999)
        self.qspin_wait_code_timeout.setProperty("value", 90)
        self.qspin_wait_code_timeout.setObjectName("qspin_wait_code_timeout")
        self.horizontalLayout_40.addWidget(self.qspin_wait_code_timeout)
        self.verticalLayout_23.addWidget(self.frame_wait_code_timeout)
        self.frame_otp_service = QtWidgets.QFrame(parent=self.setting_otp_service_group)
        self.frame_otp_service.setStyleSheet("border: 0;")
        self.frame_otp_service.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_otp_service.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_otp_service.setObjectName("frame_otp_service")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_otp_service)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_otp_service = QtWidgets.QLabel(parent=self.frame_otp_service)
        self.label_otp_service.setStyleSheet("color: #000;")
        self.label_otp_service.setObjectName("label_otp_service")
        self.horizontalLayout_41.addWidget(self.label_otp_service)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem9)
        self.otp_service_select_options = QtWidgets.QComboBox(parent=self.frame_otp_service)
        self.otp_service_select_options.setMinimumSize(QtCore.QSize(150, 35))
        self.otp_service_select_options.setMaximumSize(QtCore.QSize(150, 35))
        self.otp_service_select_options.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5;\n"
"    border: 2px solid #d3d3d3;\n"
"    border-radius: 5px;\n"
"    padding: 5px 4px;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #4caf50;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #90caf9;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    min-height: 40px;\n"
"    border: 1px solid rgb(168, 168, 168);\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    selection-background-color: lightblue;\n"
"}")
        self.otp_service_select_options.setObjectName("otp_service_select_options")
        self.otp_service_select_options.addItem("")
        self.horizontalLayout_41.addWidget(self.otp_service_select_options)
        self.verticalLayout_23.addWidget(self.frame_otp_service)
        self.frame_otp_service_api_key = QtWidgets.QFrame(parent=self.setting_otp_service_group)
        self.frame_otp_service_api_key.setStyleSheet("border: 0;")
        self.frame_otp_service_api_key.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_otp_service_api_key.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_otp_service_api_key.setObjectName("frame_otp_service_api_key")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_otp_service_api_key)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_otp_service_api_key = QtWidgets.QLabel(parent=self.frame_otp_service_api_key)
        self.label_otp_service_api_key.setStyleSheet("color: #000;")
        self.label_otp_service_api_key.setObjectName("label_otp_service_api_key")
        self.horizontalLayout_42.addWidget(self.label_otp_service_api_key)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem10)
        self.otp_service_api_key_input = QtWidgets.QLineEdit(parent=self.frame_otp_service_api_key)
        self.otp_service_api_key_input.setMinimumSize(QtCore.QSize(150, 35))
        self.otp_service_api_key_input.setMaximumSize(QtCore.QSize(150, 35))
        self.otp_service_api_key_input.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5;\n"
"    border: 2px solid #d3d3d3;\n"
"    border-radius: 5px;\n"
"    padding: 5px 4px;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4caf50;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid #90caf9;\n"
"}")
        self.otp_service_api_key_input.setText("")
        self.otp_service_api_key_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.otp_service_api_key_input.setObjectName("otp_service_api_key_input")
        self.horizontalLayout_42.addWidget(self.otp_service_api_key_input)
        self.verticalLayout_23.addWidget(self.frame_otp_service_api_key)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_23.addItem(spacerItem11)
        self.horizontalLayout_2.addWidget(self.setting_otp_service_group)
        spacerItem12 = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout_29.addWidget(self.setting_frame_1)
        self.verticalLayout_15.addWidget(self.page_settings_frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_right_bottom_setting = QtWidgets.QFrame(parent=self.page_setting_management)
        self.frame_right_bottom_setting.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_right_bottom_setting.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_right_bottom_setting.setStyleSheet("border: 0;\n"
"background-color: rgb(12, 103, 152);")
        self.frame_right_bottom_setting.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right_bottom_setting.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right_bottom_setting.setObjectName("frame_right_bottom_setting")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.frame_right_bottom_setting)
        self.horizontalLayout_50.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_50.setSpacing(5)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.frame_powered_by = QtWidgets.QFrame(parent=self.frame_right_bottom_setting)
        self.frame_powered_by.setStyleSheet("border: 0;")
        self.frame_powered_by.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_powered_by.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_powered_by.setObjectName("frame_powered_by")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.frame_powered_by)
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_powered_by = QtWidgets.QLabel(parent=self.frame_powered_by)
        self.label_powered_by.setStyleSheet("color: #fff;\n"
"font-weight: bold;")
        self.label_powered_by.setObjectName("label_powered_by")
        self.horizontalLayout_51.addWidget(self.label_powered_by)
        self.horizontalLayout_50.addWidget(self.frame_powered_by)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem13)
        self.verticalLayout_15.addWidget(self.frame_right_bottom_setting)
        self.stackedWidget.addWidget(self.page_setting_management)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_5.addWidget(self.frame_main_content)
        MetaAcctXpert.setCentralWidget(self.centralwidget)

        self.retranslateUi(MetaAcctXpert)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MetaAcctXpert)

    def retranslateUi(self, MetaAcctXpert):
        _translate = QtCore.QCoreApplication.translate
        MetaAcctXpert.setWindowTitle(_translate("MetaAcctXpert", "Masood Meta Tool"))
        self.label_version.setText(_translate("MetaAcctXpert", "Version"))
        self.version.setText(_translate("MetaAcctXpert", "1.0.0.1"))
        self.toolButton_facebook.setText(_translate("MetaAcctXpert", "Facebook"))
        self.toolButton_settings.setText(_translate("MetaAcctXpert", "Settings"))
        self.fb_creator_label.setText(_translate("MetaAcctXpert", "Facebook"))
        self.cpu_ram_label_fb_creator.setText(_translate("MetaAcctXpert", "CPU: 3.2% | RAM: 12.5%"))
        self.label_all_fb_creator.setText(_translate("MetaAcctXpert", "Total:"))
        self.label_count_all_fb_creator.setText(_translate("MetaAcctXpert", "0"))
        self.label_selected_fb_creator.setText(_translate("MetaAcctXpert", "Selected:"))
        self.label_count_selected_fb_creator.setText(_translate("MetaAcctXpert", "0"))
        self.label_live_fb_creator.setText(_translate("MetaAcctXpert", "Live:"))
        self.label_live_count_fb_creator.setText(_translate("MetaAcctXpert", "0"))
        self.label_die_fb_creator.setText(_translate("MetaAcctXpert", "Die:"))
        self.label_die_count_fb_creator.setText(_translate("MetaAcctXpert", "0"))
        self.label_error_fb_creator.setText(_translate("MetaAcctXpert", "Error:"))
        self.label_error_count_fb_creator.setText(_translate("MetaAcctXpert", "0"))
        self.label_fb_verified.setText(_translate("MetaAcctXpert", "Verified:"))
        self.label_fb_verified_count.setText(_translate("MetaAcctXpert", "0"))
        self.label_fb_unverified.setText(_translate("MetaAcctXpert", "Unverified:"))
        self.label_fb_unverified_count.setText(_translate("MetaAcctXpert", "0"))
        self.setting_label.setText(_translate("MetaAcctXpert", "Settings"))
        self.cpu_ram_label_setting.setText(_translate("MetaAcctXpert", "CPU: 3.2% | RAM: 12.5%"))
        self.basic_configuration.setTitle(_translate("MetaAcctXpert", "Basic Configuration"))
        self.facebook_max_threads_label.setText(_translate("MetaAcctXpert", "No. Threads"))
        self.label_enable_proxy.setText(_translate("MetaAcctXpert", "Use Proxies"))
        self.radio_button_enable_proxy.setText(_translate("MetaAcctXpert", "On"))
        self.radio_button_disable_proxy.setText(_translate("MetaAcctXpert", "Off"))
        self.label_proxy_type.setText(_translate("MetaAcctXpert", "Proxy Type"))
        self.radio_button_http.setText(_translate("MetaAcctXpert", "HTTP"))
        self.radio_button_https.setText(_translate("MetaAcctXpert", "HTTPS"))
        self.radio_button_socks5.setText(_translate("MetaAcctXpert", "SOCKS5"))
        self.setting_otp_service_group.setTitle(_translate("MetaAcctXpert", "OTP Service"))
        self.label_wait_code_timeout.setText(_translate("MetaAcctXpert", "Code time out (s)"))
        self.label_otp_service.setText(_translate("MetaAcctXpert", "Service"))
        self.otp_service_select_options.setItemText(0, _translate("MetaAcctXpert", "Mailtm"))
        self.label_otp_service_api_key.setText(_translate("MetaAcctXpert", "API key"))
        self.label_powered_by.setText(_translate("MetaAcctXpert", "© 2025 Powered by endpointsynergy"))
